// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vhajlhybknihsceugbhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZoYWpsaHlia25paHNjZXVnYmhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTQ4NDQsImV4cCI6MjA2OTk3MDg0NH0.Pt4K6ERG3tFriU8DFeRBi4uOQ_SwYLJlSj_FM8g5Pck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});